Provide a precise value for "oldest block identifier"
ElrondNetwork/rosetta pull request #47
Opened 2022-09-25 18:05 UTC by andreibancioiu

2022-09-26 08:46 UTC, iulianpascalau approved these changes

2022-09-26 09:21 UTC, AdoAdoAdo reviewed
can you create a feat branch and target this PR to that branch?
otherwise we will merge this to master but it will use functionality that is not yet released on mainnet.

2022-09-26 09:40 UTC, AdoAdoAdo requested changes
please reference the elrond-go tag that has the API used here

2022-09-27 06:52 UTC, andreibancioiu commented
> can you create a feat branch and target this PR to that branch? otherwise we will merge this to master but it will use functionality that is not yet released on mainnet.

We should merge into `main`, as rosetta is a standalone application, with a lifecycle that does not necessarily overlap with the node lifecycle - furthermore, in the past it was always connected to non-mainnet-version observers - but slightly newer versions, instead.

2022-09-27 06:55 UTC, iulianpascalau approved these changes

2022-09-27 07:56 UTC, AdoAdoAdo approved these changes

2022-09-27 07:59 UTC, merged